image: docker
services:
  - docker:dind

stages:
  - build
  - test

variables:
  IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"

before_script:
  - docker version
  - echo IMAGE=$IMAGE
  - docker pull byrnedo/alpine-curl
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

test:
  stage: test
  script:
    - docker pull $IMAGE
    - sh test.sh $IMAGE
